import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'package:game_frontend/Game/lobby.dart';
import 'package:game_frontend/backup/game_room_create.dart';
import 'package:game_frontend/backup/ingame.dart';
import 'package:game_frontend/backup/signed_main_page.dart';
import 'package:game_frontend/dto/gameroom-dto.dart';

// void main() {
//   runApp(const GameLobby());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Game_Lobby extends StatelessWidget {
  const Game_Lobby({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          GameRoom(),
        ]),
      ),
    );
  }
}

class GameRoom extends StatefulWidget {
  const GameRoom({super.key});

  @override
  _GameRoomState createState() => _GameRoomState();
}

class _GameRoomState extends State<GameRoom> {
  final Dio dio = Dio();
  List<GameRoomsDTO> _gamerooms = [];

  @override
  void initState() {
    super.initState();
    fetchGameRooms();
  }

  Future<void> fetchGameRooms() async {
    try {
      final Response response =
          await dio.get('http://localhost:8080/page/main');
      if (response.statusCode == 200) {
        Map<String, dynamic> data = response.data;
        List<dynamic> gameRooms = data['gameRooms'];
        List<GameRoomsDTO> gameRooms_instance = gameRooms.map((roomData) {
          return GameRoomsDTO(
            roomPassword: roomData['room_password'],
            roomName: roomData['room_name'],
            roomSize: roomData['room_size'],
            roomGoal: roomData['room_goal'],
          );
        }).toList();
        setState(() {
          _gamerooms = gameRooms_instance;
        });
      } else {
        setState(() {
          print('Error: ${response.statusCode}');
        });
      }
    } catch (e) {
      setState(() {
        print('Error: $e');
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1600,
          height: 960,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFFF2F2F2)),
          child: Stack(
            children: [
              ElevatedButton(
                onPressed: () {
                  fetchGameRooms();
                },
                child: const Text('Fetch Game Rooms'),
              ),
              ElevatedButton(
                onPressed: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => LobbyPage()));
                },
                child: const Text('Create Room'),
              ),
              Positioned(
                //top btn
                left: 50,
                top: 20,
                child: SizedBox(
                  width: 1500,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        //home btn
                        left: 0,
                        top: 0,
                        child: InkWell(
                          onTap: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => Main_Signed_Page()));
                            print('Home 버튼이 눌렸습니다.');
                          },
                          borderRadius: BorderRadius.circular(16),
                          child: SizedBox(
                            width: 190,
                            height: 60,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Container(
                                    width: 190,
                                    height: 60,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFF758CFF),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(16),
                                      ),
                                    ),
                                  ),
                                ),
                                const Positioned(
                                  left: 22,
                                  top: 18,
                                  child: SizedBox(
                                    width: 146,
                                    height: 23,
                                    child: const Center(
                                      child: Text(
                                        'HOME',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 24,
                                          fontFamily: 'Press Start 2P',
                                          fontWeight: FontWeight.w400,
                                          height: 0.07,
                                          letterSpacing: 0.96,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        //logout btn
                        left: 1310,
                        top: 0,
                        child: SizedBox(
                          width: 190,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 190,
                                  height: 60,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF758CFF),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(16),
                                    ),
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 18,
                                top: 15,
                                child: SizedBox(
                                  width: 153,
                                  height: 29,
                                  child: const Center(
                                    child: Text(
                                      'LOGOUT',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 24,
                                        fontFamily: 'Press Start 2P',
                                        fontWeight: FontWeight.w400,
                                        height: 0.07,
                                        letterSpacing: 0.96,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                //middle layout
                left: 52,
                top: 94,
                child: SizedBox(
                  width: 1501,
                  height: 748,
                  child: Stack(
                    children: [
                      Positioned(
                        //user profile
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 424,
                          height: 748,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: Color(0xFF080808),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16.97),
                            ),
                            shadows: const [
                              BoxShadow(
                                color: Color(0x7FFFFFFF),
                                blurRadius: 2.83,
                                offset: Offset(0, 2.83),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 34,
                                top: 34,
                                child: Container(
                                  width: 355.80,
                                  height: 680.17,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF1B1B1B),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(2.83),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        //user image
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 356,
                                          height: 356,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFD9D9D9),
                                            shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(8)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        //user data
                                        left: -8,
                                        top: 393,
                                        child: Container(
                                          width: 369,
                                          height: 248,
                                          child: Stack(
                                            children: [
                                              const Positioned(
                                                //user name
                                                left: 8,
                                                top: 0,
                                                child: SizedBox(
                                                  width: 230,
                                                  height: 52,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 16,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 214,
                                                          height: 20,
                                                          child: Text(
                                                            'MARIO',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 230,
                                                          height: 20,
                                                          child: Text(
                                                            'USERNAME',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              const Positioned(
                                                //user win
                                                left: 0,
                                                top: 102,
                                                child: SizedBox(
                                                  width: 120,
                                                  height: 52,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            'WIN',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            '0',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              const Positioned(
                                                //user lose
                                                left: 120,
                                                top: 102,
                                                child: SizedBox(
                                                  width: 120,
                                                  height: 52,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            '0',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            'LOSE',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                //user draw
                                                left: 242,
                                                top: 102,
                                                child: Container(
                                                  width: 120,
                                                  height: 52,
                                                  child: const Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            '0',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 120,
                                                          height: 20,
                                                          child: Text(
                                                            'DRAW',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                //user winrate
                                                left: 8,
                                                top: 196,
                                                child: Container(
                                                  width: 230,
                                                  height: 52,
                                                  child: const Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 230,
                                                          height: 20,
                                                          child: Text(
                                                            '0 %',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  -2.40,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 230,
                                                          height: 20,
                                                          child: Text(
                                                            'WIN RATE',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              const Positioned(
                                                //user tier
                                                left: 238,
                                                top: 196,
                                                child: SizedBox(
                                                  width: 131,
                                                  height: 52,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 32,
                                                        child: SizedBox(
                                                          width: 131,
                                                          height: 20,
                                                          child: Text(
                                                            'TIER',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 131,
                                                          height: 20,
                                                          child: Text(
                                                            'RANK',
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              color:
                                                                  Colors.white,
                                                              fontSize: 24,
                                                              fontFamily:
                                                                  'Press Start 2P',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0.07,
                                                              letterSpacing:
                                                                  0.96,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 452,
                        top: 0,
                        child: Container(
                          width: 1049,
                          height: 748,
                          decoration: BoxDecoration(
                            color: Color(0xFF080808),
                            borderRadius: BorderRadius.circular(16),
                            boxShadow: const [
                              BoxShadow(
                                color: Color(0x7FFFFFFF),
                                blurRadius: 2.83,
                                offset: Offset(0, 2.83),
                              ),
                            ],
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 34,
                                top: 34,
                                child: Container(
                                  width: 980.80,
                                  height: 680.17,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF1B1B1B),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(2.83),
                                    ),
                                  ),
                                  child: Column(
                                    children: [
                                      const SizedBox(
                                        width: 848.09,
                                        height: 33,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 575.11,
                                              top: 0,
                                              child: SizedBox(
                                                width: 272.98,
                                                height: 32,
                                                child: Text(
                                                  'name',
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 24,
                                                    fontFamily:
                                                        'Press Start 2P',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0,
                                                    letterSpacing: -0.60,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 119.62,
                                              top: 1,
                                              child: SizedBox(
                                                width: 466.22,
                                                height: 32,
                                                child: Text(
                                                  'Room name',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 24,
                                                    fontFamily:
                                                        'Press Start 2P',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0,
                                                    letterSpacing: -0.60,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 0,
                                              top: 1,
                                              child: SizedBox(
                                                width: 84.86,
                                                height: 32,
                                                child: Text(
                                                  'No.',
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 24,
                                                    fontFamily:
                                                        'Press Start 2P',
                                                    fontWeight: FontWeight.w400,
                                                    height: 0,
                                                    letterSpacing: -0.60,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Expanded(
                                        child: SingleChildScrollView(
                                          child: Column(
                                            children:
                                                List.generate(10, (index) {
                                              return Padding(
                                                padding:
                                                    const EdgeInsets.all(8.0),
                                                child: Container(
                                                  width: 959,
                                                  height: 73,
                                                  decoration: BoxDecoration(
                                                    color: Colors.white,
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            16),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      const Positioned(
                                                        left: 28,
                                                        top: 24,
                                                        child: SizedBox(
                                                          width: 774.77,
                                                          height: 32,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 582.61,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 192.16,
                                                                  height: 32,
                                                                  child: Text(
                                                                    'name',
                                                                    style:
                                                                        TextStyle(
                                                                      color: Colors
                                                                          .black,
                                                                      fontSize:
                                                                          24,
                                                                      fontFamily:
                                                                          'Press Start 2P',
                                                                      fontWeight:
                                                                          FontWeight
                                                                              .w400,
                                                                      height: 0,
                                                                      letterSpacing:
                                                                          -0.60,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 116.52,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 454.85,
                                                                  height: 32,
                                                                  child: Text(
                                                                    'Room name',
                                                                    style:
                                                                        TextStyle(
                                                                      color: Colors
                                                                          .black,
                                                                      fontSize:
                                                                          24,
                                                                      fontFamily:
                                                                          'Press Start 2P',
                                                                      fontWeight:
                                                                          FontWeight
                                                                              .w400,
                                                                      height: 0,
                                                                      letterSpacing:
                                                                          -0.60,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 87.75,
                                                                  height: 32,
                                                                  child: Text(
                                                                    'No.',
                                                                    style:
                                                                        TextStyle(
                                                                      color: Colors
                                                                          .black,
                                                                      fontSize:
                                                                          24,
                                                                      fontFamily:
                                                                          'Press Start 2P',
                                                                      fontWeight:
                                                                          FontWeight
                                                                              .w400,
                                                                      height: 0,
                                                                      letterSpacing:
                                                                          -0.60,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 829.10,
                                                        top: 7,
                                                        child: Container(
                                                          width: 122.95,
                                                          height: 59,
                                                          decoration:
                                                              BoxDecoration(
                                                            color: const Color(
                                                                0xFF393434),
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        16),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize:
                                                                MainAxisSize
                                                                    .min,
                                                            mainAxisAlignment:
                                                                MainAxisAlignment
                                                                    .center,
                                                            crossAxisAlignment:
                                                                CrossAxisAlignment
                                                                    .center,
                                                            children: [
                                                              ElevatedButton(
                                                                onPressed: () => {
                                                                  Navigator.push(
                                                                      context,
                                                                      MaterialPageRoute(
                                                                          builder: (context) => IngameLobby2()))
                                                                  }, 
                                                                child: const 
                                                                  Text('JOIN'),
                                                              ),
                                                              // Text(
                                                              //   'JOIN',
                                                              //   style:
                                                              //       TextStyle(
                                                              //     color: Colors
                                                              //         .white,
                                                              //     fontSize: 20,
                                                              //     fontFamily:
                                                              //         'Press Start 2P',
                                                              //     fontWeight:
                                                              //         FontWeight
                                                              //             .w400,
                                                              //     height: 0.07,
                                                              //     letterSpacing:
                                                              //         -0.60,
                                                              //   ),
                                                              // ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              );
                                            }),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                //bottom btn
                left: 50,
                top: 862,
                child: SizedBox(
                  width: 1500,
                  height: 70,
                  child: Stack(
                    children: [
                      Positioned(
                        // setting btn
                        left: 0,
                        top: 0,
                        child: InkWell(
                          onTap: () {
                            // Navigator.push(
                            //     context,
                            //     MaterialPageRoute(
                            //         builder: (context) => CreateRoomStart()));
                            print('Setting 버튼이 눌렸습니다.');
                          },
                          borderRadius: BorderRadius.circular(16),
                          child: SizedBox(
                            width: 220,
                            height: 70,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Container(
                                    width: 220,
                                    height: 70,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFFC8C5C2),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(16),
                                      ),
                                    ),
                                  ),
                                ),
                                const Positioned(
                                  left: 22,
                                  top: 17,
                                  child: SizedBox(
                                    width: 176,
                                    height: 36,
                                    child: const Center(
                                      child: Text(
                                        'SETTING',
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 24,
                                          fontFamily: 'Press Start 2P',
                                          fontWeight: FontWeight.w400,
                                          height: 0.07,
                                          letterSpacing: 0.96,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1175,
                        top: 0,
                        child: SizedBox(
                          width: 325,
                          height: 70,
                          child: InkWell(
                            onTap: () {
                              Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                      builder: (context) => Create_Room()));
                              print('Create Room');
                            },
                            borderRadius: BorderRadius.circular(16),
                            child: Container(
                              width: 325,
                              height: 70,
                              decoration: BoxDecoration(
                                color: Color(0xFFC8C5C2),
                                borderRadius: BorderRadius.circular(16),
                              ),
                              child: const Center(
                                child: Text(
                                  'CREATE ROOM',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 24,
                                    fontFamily: 'Press Start 2P',
                                    fontWeight: FontWeight.w400,
                                    height: 0.07,
                                    letterSpacing: 0.96,
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
