import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Group4(),
        ]),
      ),
    );
  }
}

class Group4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 650,
          height: 831,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 650,
                  height: 831,
                  decoration: ShapeDecoration(
                    color: Color(0xFF1B1B1B),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              const Positioned(
                left: 0,
                top: 24,
                child: SizedBox(
                  width: 650,
                  height: 47,
                  child: Text(
                    'GAME RANKING',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.02,
                      letterSpacing: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 86,
                child: Container(
                  width: 556,
                  height: 646,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF353535),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 753.64,
                child: Container(
                  width: 152,
                  height: 48.36,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 48.36,
                          decoration: ShapeDecoration(
                            color: Color(0xFF758CFF),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 6.36,
                        child: SizedBox(
                          width: 152,
                          height: 37,
                          child: Text(
                            'BACK',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24,
                              fontFamily: 'Press Start 2P',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                              letterSpacing: 0.96,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 106,
                child: Container(
                  width: 499.74,
                  height: 38,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 98,
                        top: 0,
                        child: SizedBox(
                          width: 213.49,
                          child: Text(
                            'USER NAME',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Press Start 2P',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                              letterSpacing: 0.80,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 381,
                        top: 0,
                        child: SizedBox(
                          width: 118.74,
                          child: Text(
                            'POINT',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Press Start 2P',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                              letterSpacing: 0.80,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 70.78,
                          child: Text(
                            'NO.',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Press Start 2P',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                              letterSpacing: 0.80,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 144,
                top: 159,
                child: SizedBox(
                  width: 249,
                  child: Text(
                    'TEST USER1',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 398,
                top: 160,
                child: SizedBox(
                  width: 196,
                  child: Text(
                    '1234 PT.',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 51,
                top: 159,
                child: SizedBox(
                  width: 71,
                  child: Text(
                    '1',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 144,
                top: 192,
                child: SizedBox(
                  width: 249,
                  child: Text(
                    'TEST USER2',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 398,
                top: 193,
                child: SizedBox(
                  width: 196,
                  child: Text(
                    '1000 PT.',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 51,
                top: 192,
                child: SizedBox(
                  width: 71,
                  child: Text(
                    '2',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Press Start 2P',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                      letterSpacing: 0.80,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
