import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MainPageUnsign(),
        ]),
      ),
    );
  }
}

class MainPageUnsign extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1600,
          height: 960,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF2F2F2)),
          child: Stack(
            children: [
              Positioned(
                left: 69,
                top: 102,
                child: Text(
                  'Pin-Pong Game',
                  style: TextStyle(
                    color: Color(0xFF333333),
                    fontSize: 64,
                    fontFamily: 'Press Start 2P',
                    fontWeight: FontWeight.w400,
                    height: 0.02,
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 218,
                child: Text(
                  ':team 5',
                  style: TextStyle(
                    color: Color(0xFF333333),
                    fontSize: 64,
                    fontFamily: 'Press Start 2P',
                    fontWeight: FontWeight.w400,
                    height: 0.02,
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 443,
                child: Container(
                  width: 631,
                  height: 87,
                  padding: const EdgeInsets.symmetric(horizontal: 42.48, vertical: 28.32),
                  decoration: ShapeDecoration(
                    color: Color(0xFF758CFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2357.89),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'LOGIN',
                        style: TextStyle(
                          color: Color(0xFF141414),
                          fontSize: 37.76,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w700,
                          height: 0.03,
                          letterSpacing: 1.51,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 575,
                child: Container(
                  width: 631,
                  padding: const EdgeInsets.symmetric(horizontal: 42.48, vertical: 28.32),
                  decoration: ShapeDecoration(
                    color: Color(0xFFC8C5C2),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2357.89),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'SIGN UP',
                        style: TextStyle(
                          color: Color(0xFF141414),
                          fontSize: 37.76,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w700,
                          height: 0.03,
                          letterSpacing: 1.51,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1137.77,
                top: -55,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.26),
                  child: Container(
                    width: 751.85,
                    height: 1019.13,
                    decoration: ShapeDecoration(
                      image: DecorationImage(
                        image: NetworkImage("https://via.placeholder.com/752x1019"),
                        fit: BoxFit.fill,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}